config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/index'
  post 'home/upload'

  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'

  get 'report', to: 'report#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result_item.rb
class ResultItem < ApplicationRecord
end

app/models/search_metadata.rb
class SearchMetadata < ApplicationRecord
  self.table_name = 'search_metadata'

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true

  has_many :search_metadata, class_name: 'SearchMetadata'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Localization

  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def authorized
    redirect_to '/welcome' unless logged_in?
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/controllers/concerns/localization.rb
module Localization
  extend ActiveSupport::Concern

  included do
    before_action :set_locale

    protected

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    private

    def default_url_options
      { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def upload
    keywords_params.each do |keyword|
      SearchCrawlerWorker.perform_async(current_user.id, keyword)
    end
  end

  private

  def keywords_params
    keywords_params = params.require(:keywords)
    keywords_params.compact.map! { |keyword| CGI.escape(keyword.strip) }
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
    @search_metadata = current_user.search_metadata.order(created_at: :desc)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def welcome
    redirect_to '/' if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:username, :password)
    @user = User.create(user_params)
    session[:user_id] = @user.id

    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3" style="margin-top: 200px">
      <h1 class="text-center">Scrawler Practice</h1>

      <% if logged_in? %>
        <p class="text-center">Hi, <%= current_user.username %></p>
      <%end%>

      <form id="csvForm" class="offset-md-4">
        <div class="form-group">
          <div class="input-group mb-3">
            <div class="form-group">
              <label for="files">Upload a CSV formatted file:</label>
              <input type="file" id="files" class="form-control-file" accept=".csv" required />
            </div>
          </div>
        </div>
        <div class="form-group">
          <button type="submit" id="submit-file" class="btn btn-primary">Upload File</button>
          <div class="btn btn-link">
            <%= link_to "View Report", report_path %>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>'>
  <head>
    <title>NimbleTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/report/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3" style="margin-top: 100px">
      <%= link_to "Home", home_index_path %>

      <h1 class="text-center">Listing Search metadata by keywords</h1>

      <table class="table">
        <thead>
        <tr>
          <th scope="col">Keyword</th>
          <th scope="col">Number of ads</th>
          <th scope="col">Number of links</th>
          <th scope="col">Number of all results</th>
          <th scope="col">Searched time</th>
        </tr>
        </thead>

        <tbody>
        <% @search_metadata.each do |info| %>
          <tr>
            <td><%= CGI.unescape(info.keyword) %></td>
            <td><%= info.num_of_ads %></td>
            <td><%= info.num_of_links %></td>
            <td><%= info.num_of_all_results %></td>
            <td><%= info.search_time %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3" style="margin-top: 200px">
      <h1 class="text-center">Sign up</h1>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :username %><br>
          <%= f.text_field :username, class: 'form-control' %><br>
          <%= f.label :password %><br>
          <%= f.password_field :password, class: 'form-control' %><br>
          <%= f.submit nil, class: 'btn btn-primary' %>
        </div>
      <%end%>
    </div>
  </div>
</div>